name: travelerapp
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  video_player: ^2.4.6
  get: ^4.6.5
  get_storage: ^2.0.3
  flutter_screenutil: ^5.5.3+2
  shared_preferences: ^2.0.15
  smooth_page_indicator: ^1.0.0+2
  google_nav_bar: ^5.0.6
  flutter_map:
  line_icons: ^2.0.1
  badges: ^2.0.3
  flutter_cache_manager: ^3.3.0
  flutter_staggered_grid_view: ^0.6.2
  linear_progress_bar: ^1.1.0
  anim_search_bar: ^2.0.2
  flutter_weather_bg_null_safety: ^1.0.0
  open_weather_widget: ^0.0.3
  drop_down_list: ^0.0.3
  sign_button: ^2.0.2
  font_awesome_flutter: ^10.1.0
  expandable_text: ^2.3.0
  percent_indicator: ^4.2.2
  stop_watch_timer: ^1.5.0
  accordion: ^2.5.1
  snapping_sheet: ^3.1.0
  google_fonts: ^3.0.1
  flutter_svg: ^1.1.3
  chewie: ^1.3.4
  flutter_switch: ^0.3.2
  cached_network_image: ^3.2.1
  animated_bottom_navigation_bar: ^1.0.1
  modal_bottom_sheet: ^2.1.0
  blurrycontainer: ^1.0.2
  contactus: ^1.2.0
  #
  rxdart: ^0.27.5
  dio: ^4.0.6
  intl: ^0.17.0
  http: ^0.13.5




  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  location: ^4.4.0
  focused_menu: ^1.0.5
  loading_indicator: ^3.1.0
  url_launcher: ^6.1.5
  flutter_typeahead: ^4.0.0
  flutter_cube: ^0.1.1
  audioplayers: ^1.0.1
  qr_code_scanner: ^1.0.1
  flutter_model_viewer: ^0.0.7
  internet_connection_checker: ^0.0.1+4
  connectivity_plus: ^2.3.9
  firebase_core: ^1.24.0
  firebase_messaging: ^13.1.0
  flutter_local_notifications: ^12.0.0
  cloud_firestore: ^3.5.1
  material_dialogs: ^1.1.3
  firebase_auth: ^3.11.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/image/
    - assets/image/welcomePage/
    - assets/video/
    - assets/3d/
    - assets/3d/jet/
    - assets/3d/wolf/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/font/Roboto-Regular.ttf
          weight: 400
        - asset: assets/font/Roboto-Medium.ttf
          weight: 500
        - asset: assets/font/Roboto-Bold.ttf
          weight: 700
        - asset: assets/font/Roboto-Black.ttf
          weight: 900
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages